### ISSUE TITLE
[Bug] Importing spritesheets (png) overwrites existing sprites

### ISSUE THREAD

**Issue by the-overdriven** [ottools/ObjectBuilder#38]
Importing png straight into object has a side effect of replacing existing sprites that other objects are using, so it means it will affect all other objects that are using the same sprite.

Instead creating new sprites from imported file, it is overwriting existing sprites.

How to reproduce with Duplicate:
![Recording 2022-02-28 at 01 02 37 (1)](https://user-images.githubusercontent.com/100090726/155907557-8e93a23e-f5f5-4f5a-b77d-7b5675b405ca.gif)

How to reproduce with Export/Replace:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/100090726/155907564-618c0b4b-72c6-4ecf-bb2a-45a719d8871b.gif)

**Comment by Mignari** [comment]
This is the expected behavior if you press "Yes". To create new sprites, you need to click "No"

![Screenshot_188](https://user-images.githubusercontent.com/6242139/155911401-25a31d71-1b1c-4aa1-8c42-41c70ab97677.png)

**Comment by elewental** [comment]
@Mignari 

Using same sprite to different objects may help not making the client so heavy sometimes, perhaps is not something so impactful, and im not sure if everyone who do this way uses this reason, but I do.

And when I realize that I really need add new sprites for only one of the objects, I must replace it by hand. Well I have a suggestion for this situation.        

-  Maybe if instead of the "you want to replace the current sprites", it appears "it was found more than one object with the same sprites, select this if you want to replace only this object id" and other option at the same window "ignore and replace all" (only in cases of really having multiple objects using same sprite id -- if not, keep the actual message/mode).

- As a result, if two objects have same sprite id, and you choose to replace only the **1** (the message "it was found more than one... Replace only this...) and not the **2**, instead of replacing the **1** the same way it works now, it would work like if you're importing new sprites and replacing it automatically (it would do the work of remaking the object, once it is already configured), and then object **1** would have different sprite id from the **2**.

**Comment by the-overdriven** [comment]
@Mignari it's still bugged when you hit "No":
![Recording 2022-02-28 at 12 53 29](https://user-images.githubusercontent.com/100090726/155979444-059867da-95ac-4fd7-bed8-f39edb284107.gif)
It should update edited Object, not original one.
